### ISSUE TITLE
Small files are not fully downloaded

### ISSUE THREAD

**Issue by hotice** [marionebl/remote-share-cli#1]
Small files (I tested a few, between 100kb and 15mb) are only partially downloaded. This does not occur with larger files (I tried some files between 62mb and 300mb).

Tested using remote-share-cli version 1.0.4 in Ubuntu 16.04.

**Comment by marionebl** [comment]
Thanks for the report – I'll have a look into this!

**Comment by marionebl** [comment]
Merged `remote-share-cli` with `share-cli`, check out `share-cli@2.0` for the fix.
